### ISSUE TITLE
Update alg in JWT Headers from `ES256K` to `ES256`

### ISSUE THREAD

**Issue by dleve123** [microsoft-healthcare-madison/health-wallet-demo#29]
Looks like you [recently](https://github.com/smart-on-fhir/health-cards/pull/19/files) updated the health card implementation guide to use `ES256` instead of `ES256K` for JWT signing, but that hasn't gotten updated yet in this example implementation. We assumed that this code base reflected the most up to date decisions, that seems incorrect based off of the Git history.

Call sites to update:

- https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/61c91032e0d0f7ed3f797db4471dce7abb69ea6c/src/keys.ts#L115
- https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/bf9de724826d157689f0e0dbb3ab8926f6a32990/src/VerifierLogic.ts#L51

---

Happy to handle this change once you confirm this is desired.

cc @jmandel

**Comment by jmandel** [comment]
These are merged in http://dev.c19.cards (https://github.com/microsoft-healthcare-madison/health-wallet-demo/commits/dev) -- let me know if this is working for you!

(Plan is to merge into master once others have these updates working, too -- so would love your experience here.)

**Comment by dleve123** [comment]
Ah gotcha – didn't review the `dev` branch!

> (Plan is to merge into master once others have these updates working, too -- so would love your experience here.)

Like once others QA this dev branch? Or when other orgs update their implementations to be aligned with dev?

Seems like there might be a bug on the dev build: Preparing the SIOP Response from the Holder to the Issuer by clicking "Share this card" is leading to an exception in [`prepareSiopResponse`](https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/5751d96caa302cc83ea2c224b70893a61d308183/src/holder.ts#L234).

![siop-response-preparation-error](https://user-images.githubusercontent.com/1561546/104077178-a3f4f600-51e6-11eb-9b52-63f3e3453480.png)

Confirmed this isn't present on the main branch.

**Comment by jmandel** [comment]
Thanks for the report -- I'll debug!
