### ISSUE TITLE
Failure in Redirecting to Verifier URL Manually

### ISSUE THREAD

**Issue by madaster97** [microsoft-healthcare-madison/health-wallet-demo#31]
# Issue
Once you establish a set of VCs in the "Holder", you have the option to manually input a "verifier" URL to send them to by clicking the scanner button in the bottom-left.

![image](https://user-images.githubusercontent.com/68160869/104625968-f311af80-565a-11eb-9981-8d1740ad29e8.png)

I was attempting to navigate to this libs [example verifier](https://c19.cards/venue), when I came across the following issue. 

Attempting to input a manual URL (and likely via QR code too), doesn't do anything except throw a console error.

![image](https://user-images.githubusercontent.com/68160869/104626220-3f5cef80-565b-11eb-845c-a37b7631f06b.png)

**Comment by jmandel** [comment]
You see this error when you paste in a did siop request URL like

    openid://?response_type=id_token&scope=did_authn&request_uri=https%3A%2F%2Fc19.cards%2Fapi%2Fsiop%2FyMowgX09nH5bUM4r2Qc7aA&client_id=https%3A%2F%2Fc19.cards%2Fapi%2Fsiop

? (I got this example by "copy link" on the QR from your venue link above.) This is working for me.

**Comment by madaster97** [comment]
Yep I did not understand DID SIOP when I made this. What you have above works for me too!

I think I was trying to ask the wallet to be a relying party when I made this... I understand what's happening here now.
