### ISSUE TITLE
error running in docker  - npm ERR! cb() never called!

### ISSUE THREAD

**Issue by TomCJones** [microsoft-healthcare-madison/health-wallet-demo#33]
windows 10
npm 15
i get this error

docker build -t health-wallet-demo .
[+] Building 1200.9s (8/13)
 => [internal] load build definition from Dockerfile                                                                                              0.1s
 => => transferring dockerfile: 329B                                                                                                              0.1s
 => [internal] load .dockerignore                                                                                                                 0.1s
 => => transferring context: 54B                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/node:13                                                                                        3.6s
 => [1/9] FROM docker.io/library/node:13@sha256:70d4fffcab39a1f9f7161d58e674ddcc56c7f0724196b68d52a87bab15cb4a04                                561.7s
 => => resolve docker.io/library/node:13@sha256:70d4fffcab39a1f9f7161d58e674ddcc56c7f0724196b68d52a87bab15cb4a04                                  0.0s
 => => sha256:70d4fffcab39a1f9f7161d58e674ddcc56c7f0724196b68d52a87bab15cb4a04 1.21kB / 1.21kB                                                    0.0s
 => => sha256:2b9604a36e4911d15d2916dac4f1d853e2da612e9bb77df1016f8a51b3e333a1 7.88kB / 7.88kB                                                    0.0s
 => => sha256:1c6172af85ee14a8db5a3a51d406b768dfa94d196c06d0d06d591507cf8199f0 45.38MB / 45.38MB                                                199.6s
 => => sha256:b194b0e3c928807cfabf081055a117585ba5bf6697f65b2fede02225a5d73ad2 10.80MB / 10.80MB                                                 56.4s
 => => sha256:1e8d7127072cdbaae1935656444c3ec2bef8882c8c14d459e3a92ca1dd313c28 2.21kB / 2.21kB                                                    0.0s
 => => sha256:1f5ec00f35d5b2d1db6b8e925a3005c1a285365775028db0339903ddaeec4763 4.34MB / 4.34MB                                                   33.1s
 => => sha256:93b1353672b6861da5f1b58b0eca02ec10373a25d2898bddafa1b4bae2271c55 50.08MB / 50.08MB                                                286.1s
 => => sha256:3d7f38db3cca2c74df9a146d8419f5bf79d79b18de9eaee6351dccde16ab1f4a 214.91MB / 214.91MB                                              552.7s
 => => sha256:21e102f9fe89a18627c0ce50945bd1e0a11d0fecd4800bbbd999944d3940efc6 4.16kB / 4.16kB                                                  200.1s
 => => extracting sha256:1c6172af85ee14a8db5a3a51d406b768dfa94d196c06d0d06d591507cf8199f0                                                         1.6s
 => => sha256:d5431b24825a3297da35afe3d32786e01ec3fe7a8d1685adf59f82138e916e10 34.44MB / 34.44MB                                                358.6s
 => => extracting sha256:b194b0e3c928807cfabf081055a117585ba5bf6697f65b2fede02225a5d73ad2                                                         0.3s
 => => extracting sha256:1f5ec00f35d5b2d1db6b8e925a3005c1a285365775028db0339903ddaeec4763                                                         0.1s
 => => sha256:f780e3352c1809c08a5e6e4168206425ce703018baae8d6efd8d18efb101405b 2.38MB / 2.38MB                                                  301.5s
 => => extracting sha256:93b1353672b6861da5f1b58b0eca02ec10373a25d2898bddafa1b4bae2271c55                                                         1.9s
 => => sha256:4d28937582d0e76cbe8ed78ed921823a349a8a0755f91e13648e7636c974b0b6 295B / 295B                                                      303.3s
 => => extracting sha256:3d7f38db3cca2c74df9a146d8419f5bf79d79b18de9eaee6351dccde16ab1f4a                                                         6.7s
 => => extracting sha256:21e102f9fe89a18627c0ce50945bd1e0a11d0fecd4800bbbd999944d3940efc6                                                         0.0s
 => => extracting sha256:d5431b24825a3297da35afe3d32786e01ec3fe7a8d1685adf59f82138e916e10                                                         1.5s
 => => extracting sha256:f780e3352c1809c08a5e6e4168206425ce703018baae8d6efd8d18efb101405b                                                         0.1s
 => => extracting sha256:4d28937582d0e76cbe8ed78ed921823a349a8a0755f91e13648e7636c974b0b6                                                         0.0s
 => [internal] load build context                                                                                                                 0.4s
 => => transferring context: 1.14MB                                                                                                               0.3s
 => [2/9] WORKDIR /usr/src/app                                                                                                                    0.8s
 => [3/9] COPY package.json package-lock.json ./                                                                                                  0.0s
 => ERROR [4/9] RUN npm ci                                                                                                                      634.7s
------
 > [4/9] RUN npm ci:
#8 634.6 npm ERR! cb() never called!
#8 634.6
#8 634.6 npm ERR! This is an error with npm itself. Please report this error at:
#8 634.6 npm ERR!     <https://npm.community>
#8 634.7
#8 634.7 npm ERR! A complete log of this run can be found in:
#8 634.7 npm ERR!     /root/.npm/_logs/2021-01-16T20_27_55_657Z-debug.log
------
executor failed running [/bin/sh -c npm ci]: exit code: 1

**Comment by madaster97** [comment]
Is this happening consistently, or have you only seen it once?

You could try and get the logs from npm following the strategy [here](https://stackoverflow.com/questions/24192210/docker-build-npm-error-logs).

Also, what branch are you pulling from?

**Comment by jmandel** [comment]
Closing this as it hasn't been reproduced, but please reopen if this is continuing.
